version: '3.3'

services:
  react:
    build: .
    container_name: checkinweb
    ports:
      - "1000:3000"
  backend:
    build: python
    container_name: checkinbackend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    container_name: checkinmongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db